import { useState, useMemo } from "react";
import Head from 'next/head';
import dynamic from "next/dynamic";
import Navbar from '@components/Navbar';
import hljs from 'highlight.js';
// import axios from "axios";

import "react-quill/dist/quill.snow.css";
import "react-quill/dist/quill.bubble.css";
import 'highlight.js/styles/atom-one-dark.css'

export default function Quill() {

  const ReactQuill = useMemo(() => dynamic(() => {
    hljs.configure({
      languages: ['javascript', 'php', 'go']
    })
    window.hljs = hljs
    return import("react-quill")
  },
    { ssr: false, loading: () => <p className="dark:text-black">Loading ...</p> }),
    []);

  const [description, setDescription] = useState('');

  function handleDescriptionChange(e) {
    setDescription(e);
  };

  const [defaultValue, setDefaultValue] = useState(`<h2>What to expect from here on out</h2>
      <p>What follows from here is just a bunch of absolute nonsense I've written to dogfood the plugin itself. It includes every sensible typographic element I could think of, like <strong>bold text</strong>, unordered lists, ordered lists, code blocks, block quotes, <em>and even italics</em>.</p>
      <p>It's important to cover all of these use cases for a few reasons:</p>
      <ol>
        <li>We want everything to look good out of the box.</li>
        <li>Really just the first reason, that's the whole point of the plugin.</li>
        <li>Here's a third pretend reason though a list with three items looks more realistic than a list with two items.</li>
      </ol>
      <p>Now we're going to try out another header style.</p>
      <h3>Typography should be easy</h3>
      <p>So that's a header for you — with any luck if we've done our job correctly that will look pretty reasonable.</p>
      <p>Something a wise person once told me about typography is:</p>
      <blockquote><p>Typography is pretty important if you don't want your stuff to look like trash. Make it good then it won't be bad.</p></blockquote>
      <p>It's probably important that images look okay here by default as well:</p>`);

  function handleValueChange(e) {
    setDefaultValue(e);
  };

  return (
    <div>
      <Head>
        <title>React Quill</title>
        <meta name="description" description="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="dark:bg-neutral-900 min-h-screen">
        <div className="max-w-5xl mx-auto p-3">
          <h1 className="text-3xl text-neutral-800 dark:text-white font-semibold tracking-wide mb-8">
            React Quill
          </h1>

          <div className="font-normal text-lg font-sans bg-white dark:text-neutral-800 p-2 border-2 dark:border-neutral-700 rounded-lg mb-3">
            <ReactQuill
              theme="snow"
              onChange={handleDescriptionChange}
              modules={{
                // syntax: {
                //   highlight: text => hljs.highlightAuto(text).value,
                // },
                syntax: true,
                toolbar: [
                  [{ 'header': [1, 2, 3, 4, false] }],
                  [{ 'size': ['small', false, 'large', 'huge'] }],
                  [{ 'align': [] }],
                  ['bold', 'italic', 'underline', 'strike'],
                  ['blockquote', 'code-block'],
                  [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'indent': '-1' }, { 'indent': '+1' }],
                  ['link', 'image', 'video'],
                  [{ 'script': 'sub' }, { 'script': 'super' }],
                  [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
                  // [{ 'font': [] }], 
                  ['clean']
                ],
              }}
            />
          </div>

          <div className="py-8">
            {description &&
              <div >
                {description}
              </div>
            }
          </div>

          <h1 className="text-2xl text-neutral-800 dark:text-white font-semibold tracking-wide mb-4">
            Read Only
          </h1>

          <div className="font-normal text-lg font-sans bg-white dark:text-neutral-800 p-2 border-2 dark:border-neutral-700 rounded-lg mb-3">
            <ReactQuill
              theme="bubble"
              value={description}
              readOnly
            />
          </div>

          <h1 className="text-2xl text-neutral-800 dark:text-white font-semibold tracking-wide my-4">
            Preview
          </h1>

          <div className="prose dark:prose-invert" dangerouslySetInnerHTML={{ __html: description }} />

          <h1 className="text-3xl mt-8 text-neutral-800 dark:text-white font-semibold tracking-wide mb-8">
            React Quill Default Value
          </h1>

          <div className="font-normal text-lg font-sans bg-white dark:text-neutral-800 p-2 border-2 dark:border-neutral-700 rounded-lg mb-3">
            <ReactQuill
              theme="snow"
              value={defaultValue}
              onChange={handleValueChange}
            />
          </div>

          <div className="py-8">
            {defaultValue &&
              <div >
                {defaultValue}
              </div>
            }
          </div>

          <h1 className="text-2xl text-neutral-800 dark:text-white font-semibold tracking-wide mb-4">
            Read Only
          </h1>

          <div className="font-normal text-lg font-sans bg-white dark:text-neutral-800 p-2 border-2 dark:border-neutral-700 rounded-lg mb-3">
            <ReactQuill
              theme="bubble"
              value={defaultValue}
              readOnly
            />
          </div>

          <h1 className="text-2xl text-neutral-800 dark:text-white font-semibold tracking-wide my-4">
            Preview
          </h1>

          <div className="prose dark:prose-invert" dangerouslySetInnerHTML={{ __html: defaultValue }} />

        </div>
      </main>
    </div>
  )
}
